services:
  starlette_admin_demo:
    container_name: starlette_admin_demo
    build: .
    restart: always
    environment:
      UPLOAD_DIR: uploads/
      ENGINE: sqlite:///demo.db?check_same_thread=false
      APP_ENV: PROD
      SECRET_KEY: ${SECRET_KEY:?SECRET_KEY must be set}
